# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'design.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QMainWindow, QPushButton,
    QSizePolicy, QStackedWidget, QVBoxLayout, QWidget)
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(837, 436)
        MainWindow.setStyleSheet(u"background-color: 	#363636")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.wg_sidebar = QWidget(self.centralwidget)
        self.wg_sidebar.setObjectName(u"wg_sidebar")
        self.wg_sidebar.setGeometry(QRect(0, 0, 71, 431))
        self.wg_sidebar.setStyleSheet(u"background-color: 	#363636")
        self.btn_config = QPushButton(self.wg_sidebar)
        self.btn_config.setObjectName(u"btn_config")
        self.btn_config.setGeometry(QRect(-1, 55, 71, 40))
        self.btn_config.setStyleSheet(u"border:none;")
        icon = QIcon()
        icon.addFile(u":/newPrefix/images/2112374.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_config.setIcon(icon)
        self.btn_config.setIconSize(QSize(40, 40))
        self.btn_bluestacks = QPushButton(self.wg_sidebar)
        self.btn_bluestacks.setObjectName(u"btn_bluestacks")
        self.btn_bluestacks.setGeometry(QRect(-1, 148, 71, 40))
        self.btn_bluestacks.setStyleSheet(u"border:none;\n"
"")
        icon1 = QIcon()
        icon1.addFile(u":/newPrefix/images/BlueStacks.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_bluestacks.setIcon(icon1)
        self.btn_bluestacks.setIconSize(QSize(40, 40))
        self.btn_msi = QPushButton(self.wg_sidebar)
        self.btn_msi.setObjectName(u"btn_msi")
        self.btn_msi.setGeometry(QRect(-1, 242, 71, 40))
        self.btn_msi.setStyleSheet(u"border:none;")
        icon2 = QIcon()
        icon2.addFile(u":/newPrefix/images/App-player-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.btn_msi.setIcon(icon2)
        self.btn_msi.setIconSize(QSize(40, 40))
        self.label = QLabel(self.wg_sidebar)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(-1, 101, 71, 20))
        self.label.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"qproperty-alignment: AlignCenter; \n"
"qproperty-wordWrap: true; \n"
"qproperty-textWrap: true;\n"
"color: white;")
        self.label.setScaledContents(False)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setIndent(-1)
        self.label_2 = QLabel(self.wg_sidebar)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(-2, 194, 81, 16))
        self.label_2.setMinimumSize(QSize(60, 0))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: white;")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.wg_sidebar)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(-1, 288, 71, 20))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color:white;")
        self.label_3.setScaledContents(False)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.reg_btn = QPushButton(self.wg_sidebar)
        self.reg_btn.setObjectName(u"reg_btn")
        self.reg_btn.setGeometry(QRect(-1, 340, 71, 40))
        self.reg_btn.setStyleSheet(u"border:none;")
        icon3 = QIcon()
        icon3.addFile(u":/newPrefix/images/regedit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.reg_btn.setIcon(icon3)
        self.reg_btn.setIconSize(QSize(50, 40))
        self.label_24 = QLabel(self.wg_sidebar)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(0, 390, 71, 20))
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(u"color:white;")
        self.label_24.setAlignment(Qt.AlignCenter)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(70, 0, 771, 431))
        self.stackedWidget.setStyleSheet(u"background-color: 	#1C1C1C")
        self.Config_page = QWidget()
        self.Config_page.setObjectName(u"Config_page")
        self.widget_13 = QWidget(self.Config_page)
        self.widget_13.setObjectName(u"widget_13")
        self.widget_13.setGeometry(QRect(0, 0, 761, 431))
        self.widget_14 = QWidget(self.widget_13)
        self.widget_14.setObjectName(u"widget_14")
        self.widget_14.setGeometry(QRect(0, 0, 771, 51))
        self.widget_14.setStyleSheet(u"background-color: 	#363636")
        self.label_4 = QLabel(self.widget_14)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 10, 771, 31))
        font1 = QFont()
        font1.setPointSize(15)
        font1.setBold(True)
        self.label_4.setFont(font1)
        self.label_4.setStyleSheet(u"color:white;\n"
"")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.widget_19 = QWidget(self.widget_13)
        self.widget_19.setObjectName(u"widget_19")
        self.widget_19.setGeometry(QRect(9, 69, 201, 361))
        self.widget_19.setStyleSheet(u"color:white;")
        self.verticalLayout_5 = QVBoxLayout(self.widget_19)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.label_34 = QLabel(self.widget_19)
        self.label_34.setObjectName(u"label_34")
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        self.label_34.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_34)

        self.label_35 = QLabel(self.widget_19)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_35)

        self.label_43 = QLabel(self.widget_19)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_43)

        self.label_45 = QLabel(self.widget_19)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_45)

        self.label_51 = QLabel(self.widget_19)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_51)

        self.label_46 = QLabel(self.widget_19)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_46)

        self.label_50 = QLabel(self.widget_19)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_50)

        self.label_47 = QLabel(self.widget_19)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_47)

        self.label_48 = QLabel(self.widget_19)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_48)

        self.label_49 = QLabel(self.widget_19)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setFont(font2)

        self.verticalLayout_5.addWidget(self.label_49)

        self.widget_20 = QWidget(self.widget_13)
        self.widget_20.setObjectName(u"widget_20")
        self.widget_20.setGeometry(QRect(220, 70, 93, 371))
        self.verticalLayout_6 = QVBoxLayout(self.widget_20)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.limp_cache = QPushButton(self.widget_20)
        self.limp_cache.setObjectName(u"limp_cache")
        self.limp_cache.setStyleSheet(u"border:none;")
        icon4 = QIcon()
        icon4.addFile(u":/newPrefix/images/7207229.png", QSize(), QIcon.Normal, QIcon.Off)
        self.limp_cache.setIcon(icon4)
        self.limp_cache.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.limp_cache)

        self.clear_temp = QPushButton(self.widget_20)
        self.clear_temp.setObjectName(u"clear_temp")
        self.clear_temp.setStyleSheet(u"border:none;")
        self.clear_temp.setIcon(icon4)
        self.clear_temp.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.clear_temp)

        self.dele_arq_logs = QPushButton(self.widget_20)
        self.dele_arq_logs.setObjectName(u"dele_arq_logs")
        self.dele_arq_logs.setStyleSheet(u"border:none;")
        self.dele_arq_logs.setIcon(icon4)
        self.dele_arq_logs.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.dele_arq_logs)

        self.del_arg_temp = QPushButton(self.widget_20)
        self.del_arg_temp.setObjectName(u"del_arg_temp")
        self.del_arg_temp.setStyleSheet(u"border:none;")
        self.del_arg_temp.setIcon(icon4)
        self.del_arg_temp.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.del_arg_temp)

        self.des_serv = QPushButton(self.widget_20)
        self.des_serv.setObjectName(u"des_serv")
        self.des_serv.setStyleSheet(u"border:none;")
        self.des_serv.setIcon(icon4)
        self.des_serv.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.des_serv)

        self.des_win_updt = QPushButton(self.widget_20)
        self.des_win_updt.setObjectName(u"des_win_updt")
        self.des_win_updt.setStyleSheet(u"border:none;")
        self.des_win_updt.setIcon(icon4)
        self.des_win_updt.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.des_win_updt)

        self.limp_cache_2 = QPushButton(self.widget_20)
        self.limp_cache_2.setObjectName(u"limp_cache_2")
        self.limp_cache_2.setStyleSheet(u"border:none;")
        self.limp_cache_2.setIcon(icon4)
        self.limp_cache_2.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.limp_cache_2)

        self.limpz_servi = QPushButton(self.widget_20)
        self.limpz_servi.setObjectName(u"limpz_servi")
        self.limpz_servi.setStyleSheet(u"border:none;")
        self.limpz_servi.setIcon(icon4)
        self.limpz_servi.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.limpz_servi)

        self.mem_ptm = QPushButton(self.widget_20)
        self.mem_ptm.setObjectName(u"mem_ptm")
        self.mem_ptm.setStyleSheet(u"border:none;")
        self.mem_ptm.setIcon(icon4)
        self.mem_ptm.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.mem_ptm)

        self.otm = QPushButton(self.widget_20)
        self.otm.setObjectName(u"otm")
        self.otm.setStyleSheet(u"border:none;")
        self.otm.setIcon(icon4)
        self.otm.setIconSize(QSize(30, 30))

        self.verticalLayout_6.addWidget(self.otm)

        self.widget_21 = QWidget(self.widget_13)
        self.widget_21.setObjectName(u"widget_21")
        self.widget_21.setGeometry(QRect(350, 70, 121, 41))
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(False)
        self.widget_21.setFont(font3)
        self.verticalLayout_7 = QVBoxLayout(self.widget_21)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.label_52 = QLabel(self.widget_21)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setFont(font2)
        self.label_52.setStyleSheet(u"color:white;")

        self.verticalLayout_7.addWidget(self.label_52)

        self.widget_22 = QWidget(self.widget_13)
        self.widget_22.setObjectName(u"widget_22")
        self.widget_22.setGeometry(QRect(470, 70, 93, 42))
        self.verticalLayout_8 = QVBoxLayout(self.widget_22)
        self.verticalLayout_8.setObjectName(u"verticalLayout_8")
        self.ten_apps = QPushButton(self.widget_22)
        self.ten_apps.setObjectName(u"ten_apps")
        self.ten_apps.setStyleSheet(u"border:none;")
        icon5 = QIcon()
        icon5.addFile(u":/newPrefix/images/4438834.png", QSize(), QIcon.Normal, QIcon.Off)
        self.ten_apps.setIcon(icon5)
        self.ten_apps.setIconSize(QSize(30, 30))

        self.verticalLayout_8.addWidget(self.ten_apps)

        self.stackedWidget.addWidget(self.Config_page)
        self.bluestacks_page = QWidget()
        self.bluestacks_page.setObjectName(u"bluestacks_page")
        self.widget = QWidget(self.bluestacks_page)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(9, 40, 141, 231))
        self.widget.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_4 = QWidget(self.widget)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(-1, 10, 141, 81))
        self.label_5 = QLabel(self.widget_4)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setStyleSheet(u"")
        self.label_5.setPixmap(QPixmap(u":/newPrefix/images/BlueStacks.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 90, 141, 20))
        self.label_12 = QLabel(self.widget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(0, 110, 141, 20))
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.download_ultra_ego_bs = QPushButton(self.widget)
        self.download_ultra_ego_bs.setObjectName(u"download_ultra_ego_bs")
        self.download_ultra_ego_bs.setGeometry(QRect(0, 180, 141, 24))
        self.download_ultra_ego_bs.setFont(font)
        self.download_ultra_ego_bs.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.widget_2 = QWidget(self.bluestacks_page)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(300, 40, 141, 231))
        self.widget_2.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_5 = QWidget(self.widget_2)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(-1, 10, 141, 81))
        self.label_7 = QLabel(self.widget_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setStyleSheet(u"")
        self.label_7.setPixmap(QPixmap(u":/newPrefix/images/BlueStacks.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_10 = QLabel(self.widget_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 90, 141, 20))
        self.label_13 = QLabel(self.widget_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 110, 141, 20))
        self.label_13.setFont(font)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.download_5_20_0_1037bs = QPushButton(self.widget_2)
        self.download_5_20_0_1037bs.setObjectName(u"download_5_20_0_1037bs")
        self.download_5_20_0_1037bs.setGeometry(QRect(0, 180, 141, 24))
        self.download_5_20_0_1037bs.setFont(font)
        self.download_5_20_0_1037bs.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.widget_3 = QWidget(self.bluestacks_page)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(580, 40, 141, 231))
        self.widget_3.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_6 = QWidget(self.widget_3)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(-1, 10, 141, 81))
        self.label_8 = QLabel(self.widget_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setStyleSheet(u"")
        self.label_8.setPixmap(QPixmap(u":/newPrefix/images/BlueStacks.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.widget_3)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(0, 90, 141, 20))
        self.label_14 = QLabel(self.widget_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 110, 141, 20))
        self.label_14.setFont(font)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.download_4_240_1002bs = QPushButton(self.widget_3)
        self.download_4_240_1002bs.setObjectName(u"download_4_240_1002bs")
        self.download_4_240_1002bs.setGeometry(QRect(0, 180, 141, 24))
        self.download_4_240_1002bs.setFont(font)
        self.download_4_240_1002bs.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.stackedWidget.addWidget(self.bluestacks_page)
        self.msi_page = QWidget()
        self.msi_page.setObjectName(u"msi_page")
        self.widget_7 = QWidget(self.msi_page)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(580, 40, 141, 231))
        self.widget_7.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_8 = QWidget(self.widget_7)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(-1, 10, 141, 81))
        self.label_15 = QLabel(self.widget_8)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setStyleSheet(u"")
        self.label_15.setPixmap(QPixmap(u":/newPrefix/images/App-player-icon.png"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.widget_7)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 90, 141, 20))
        self.label_17 = QLabel(self.widget_7)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 110, 141, 20))
        self.label_17.setFont(font)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.download_m = QPushButton(self.widget_7)
        self.download_m.setObjectName(u"download_m")
        self.download_m.setGeometry(QRect(0, 180, 141, 24))
        self.download_m.setFont(font)
        self.download_m.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.widget_9 = QWidget(self.msi_page)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setGeometry(QRect(9, 40, 141, 231))
        self.widget_9.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_10 = QWidget(self.widget_9)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(-1, 10, 141, 81))
        self.label_6 = QLabel(self.widget_10)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet(u"")
        self.label_6.setPixmap(QPixmap(u":/newPrefix/images/App-player-icon.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_18 = QLabel(self.widget_9)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 90, 141, 20))
        self.label_19 = QLabel(self.widget_9)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 110, 141, 20))
        self.label_19.setFont(font)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.download_ultra_god_msi = QPushButton(self.widget_9)
        self.download_ultra_god_msi.setObjectName(u"download_ultra_god_msi")
        self.download_ultra_god_msi.setGeometry(QRect(0, 180, 141, 24))
        self.download_ultra_god_msi.setFont(font)
        self.download_ultra_god_msi.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.label_23 = QLabel(self.widget_9)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(0, 130, 141, 20))
        self.label_23.setFont(font)
        self.label_23.setAlignment(Qt.AlignCenter)
        self.widget_11 = QWidget(self.msi_page)
        self.widget_11.setObjectName(u"widget_11")
        self.widget_11.setGeometry(QRect(300, 40, 141, 231))
        self.widget_11.setStyleSheet(u"background-color:#4F4F4F;")
        self.widget_12 = QWidget(self.widget_11)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setGeometry(QRect(-1, 10, 141, 81))
        self.label_20 = QLabel(self.widget_12)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(40, 10, 61, 51))
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setStyleSheet(u"")
        self.label_20.setPixmap(QPixmap(u":/newPrefix/images/App-player-icon.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.widget_11)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 90, 141, 20))
        self.label_22 = QLabel(self.widget_11)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(0, 110, 141, 20))
        self.label_22.setFont(font)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.download_msi5_12 = QPushButton(self.widget_11)
        self.download_msi5_12.setObjectName(u"download_msi5_12")
        self.download_msi5_12.setGeometry(QRect(0, 180, 141, 24))
        self.download_msi5_12.setFont(font)
        self.download_msi5_12.setStyleSheet(u"background-color:#1C1C1C;\n"
"color:white;\n"
"border-radius:10px;")
        self.stackedWidget.addWidget(self.msi_page)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.widget_15 = QWidget(self.page)
        self.widget_15.setObjectName(u"widget_15")
        self.widget_15.setGeometry(QRect(0, 0, 761, 431))
        self.widget_16 = QWidget(self.widget_15)
        self.widget_16.setObjectName(u"widget_16")
        self.widget_16.setGeometry(QRect(0, 0, 771, 41))
        self.widget_16.setStyleSheet(u"background-color: 	#363636")
        self.label_25 = QLabel(self.widget_16)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(0, 10, 761, 31))
        self.label_25.setFont(font1)
        self.label_25.setStyleSheet(u"color:white;")
        self.label_25.setAlignment(Qt.AlignCenter)
        self.widget_17 = QWidget(self.widget_15)
        self.widget_17.setObjectName(u"widget_17")
        self.widget_17.setGeometry(QRect(0, 60, 211, 371))
        font4 = QFont()
        font4.setBold(False)
        self.widget_17.setFont(font4)
        self.widget_17.setStyleSheet(u"color:white;")
        self.verticalLayout = QVBoxLayout(self.widget_17)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_26 = QLabel(self.widget_17)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setFont(font)

        self.verticalLayout.addWidget(self.label_26)

        self.label_27 = QLabel(self.widget_17)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setFont(font)

        self.verticalLayout.addWidget(self.label_27)

        self.label_28 = QLabel(self.widget_17)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setFont(font)

        self.verticalLayout.addWidget(self.label_28)

        self.label_29 = QLabel(self.widget_17)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setFont(font)

        self.verticalLayout.addWidget(self.label_29)

        self.label_30 = QLabel(self.widget_17)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setFont(font)

        self.verticalLayout.addWidget(self.label_30)

        self.label_31 = QLabel(self.widget_17)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setFont(font)

        self.verticalLayout.addWidget(self.label_31)

        self.label_32 = QLabel(self.widget_17)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setFont(font)

        self.verticalLayout.addWidget(self.label_32)

        self.label_33 = QLabel(self.widget_17)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setFont(font)

        self.verticalLayout.addWidget(self.label_33)

        self.verticalLayoutWidget = QWidget(self.widget_15)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(220, 50, 84, 391))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.acelerando_menu = QPushButton(self.verticalLayoutWidget)
        self.acelerando_menu.setObjectName(u"acelerando_menu")
        self.acelerando_menu.setStyleSheet(u"border:none;")
        self.acelerando_menu.setIcon(icon3)
        self.acelerando_menu.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.acelerando_menu)

        self.aumentar_capacidade = QPushButton(self.verticalLayoutWidget)
        self.aumentar_capacidade.setObjectName(u"aumentar_capacidade")
        self.aumentar_capacidade.setStyleSheet(u"border:none;")
        self.aumentar_capacidade.setIcon(icon3)
        self.aumentar_capacidade.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.aumentar_capacidade)

        self.aumente_fps = QPushButton(self.verticalLayoutWidget)
        self.aumente_fps.setObjectName(u"aumente_fps")
        self.aumente_fps.setStyleSheet(u"border:none;")
        self.aumente_fps.setIcon(icon3)
        self.aumente_fps.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.aumente_fps)

        self.des_DVR = QPushButton(self.verticalLayoutWidget)
        self.des_DVR.setObjectName(u"des_DVR")
        self.des_DVR.setStyleSheet(u"border:none;")
        self.des_DVR.setIcon(icon3)
        self.des_DVR.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.des_DVR)

        self.efeitos_visuais = QPushButton(self.verticalLayoutWidget)
        self.efeitos_visuais.setObjectName(u"efeitos_visuais")
        self.efeitos_visuais.setStyleSheet(u"border:none;")
        self.efeitos_visuais.setIcon(icon3)
        self.efeitos_visuais.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.efeitos_visuais)

        self.full_screen_fix = QPushButton(self.verticalLayoutWidget)
        self.full_screen_fix.setObjectName(u"full_screen_fix")
        self.full_screen_fix.setStyleSheet(u"border:none;")
        self.full_screen_fix.setIcon(icon3)
        self.full_screen_fix.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.full_screen_fix)

        self.game_optm = QPushButton(self.verticalLayoutWidget)
        self.game_optm.setObjectName(u"game_optm")
        self.game_optm.setStyleSheet(u"border:none;")
        self.game_optm.setIcon(icon3)
        self.game_optm.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.game_optm)

        self.red_inp_lag = QPushButton(self.verticalLayoutWidget)
        self.red_inp_lag.setObjectName(u"red_inp_lag")
        self.red_inp_lag.setStyleSheet(u"border:none;")
        self.red_inp_lag.setIcon(icon3)
        self.red_inp_lag.setIconSize(QSize(20, 20))

        self.verticalLayout_2.addWidget(self.red_inp_lag)

        self.widget_18 = QWidget(self.widget_15)
        self.widget_18.setObjectName(u"widget_18")
        self.widget_18.setGeometry(QRect(299, 59, 241, 371))
        font5 = QFont()
        font5.setPointSize(9)
        self.widget_18.setFont(font5)
        self.widget_18.setStyleSheet(u"color:white;")
        self.verticalLayout_3 = QVBoxLayout(self.widget_18)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label_36 = QLabel(self.widget_18)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_36)

        self.label_37 = QLabel(self.widget_18)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_37)

        self.label_44 = QLabel(self.widget_18)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_44)

        self.label_40 = QLabel(self.widget_18)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_40)

        self.label_38 = QLabel(self.widget_18)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_38)

        self.label_41 = QLabel(self.widget_18)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_41)

        self.label_39 = QLabel(self.widget_18)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_39)

        self.label_42 = QLabel(self.widget_18)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setFont(font2)

        self.verticalLayout_3.addWidget(self.label_42)

        self.verticalLayoutWidget_2 = QWidget(self.widget_15)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(550, 110, 77, 321))
        self.verticalLayout_4 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.des_maps = QPushButton(self.verticalLayoutWidget_2)
        self.des_maps.setObjectName(u"des_maps")
        self.des_maps.setStyleSheet(u"border:none;")
        self.des_maps.setIcon(icon3)
        self.des_maps.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_maps)

        self.des_blue = QPushButton(self.verticalLayoutWidget_2)
        self.des_blue.setObjectName(u"des_blue")
        self.des_blue.setStyleSheet(u"border:none;")
        self.des_blue.setIcon(icon3)
        self.des_blue.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_blue)

        self.des_impre = QPushButton(self.verticalLayoutWidget_2)
        self.des_impre.setObjectName(u"des_impre")
        self.des_impre.setStyleSheet(u"border:none;")
        self.des_impre.setIcon(icon3)
        self.des_impre.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_impre)

        self.des_xbox = QPushButton(self.verticalLayoutWidget_2)
        self.des_xbox.setObjectName(u"des_xbox")
        self.des_xbox.setStyleSheet(u"border:none;")
        self.des_xbox.setIcon(icon3)
        self.des_xbox.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_xbox)

        self.des_extr_desn = QPushButton(self.verticalLayoutWidget_2)
        self.des_extr_desn.setObjectName(u"des_extr_desn")
        self.des_extr_desn.setStyleSheet(u"border:none;")
        self.des_extr_desn.setIcon(icon3)
        self.des_extr_desn.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_extr_desn)

        self.des_uac = QPushButton(self.verticalLayoutWidget_2)
        self.des_uac.setObjectName(u"des_uac")
        self.des_uac.setStyleSheet(u"border:none;")
        self.des_uac.setIcon(icon3)
        self.des_uac.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_uac)

        self.des_windef = QPushButton(self.verticalLayoutWidget_2)
        self.des_windef.setObjectName(u"des_windef")
        self.des_windef.setStyleSheet(u"border:none;")
        self.des_windef.setIcon(icon3)
        self.des_windef.setIconSize(QSize(20, 20))

        self.verticalLayout_4.addWidget(self.des_windef)

        self.stackedWidget.addWidget(self.page)
        MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.btn_config, self.btn_bluestacks)
        QWidget.setTabOrder(self.btn_bluestacks, self.btn_msi)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.btn_config.setText("")
        self.btn_bluestacks.setText("")
        self.btn_msi.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Config", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Bluestacks", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Msi", None))
        self.reg_btn.setText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Regedits", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Crie um Ponto de Restaura\u00e7\u00e3o antes!", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u" Limpar Cache de Navegador", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Clear Temp", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"Deletar Arquivos de Logs", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"Deletar Arquivos Temporarios", None))
        self.label_51.setText(QCoreApplication.translate("MainWindow", u"Desabilitar_Servicos", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"Desativar Windows Update", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"Limpador de Cache", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"Limpeza De Servi\u00e7os", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"Memory Optmizer", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"Otimiza\u00e7\u00e3o", None))
        self.limp_cache.setText("")
        self.clear_temp.setText("")
        self.dele_arq_logs.setText("")
        self.del_arg_temp.setText("")
        self.des_serv.setText("")
        self.des_win_updt.setText("")
        self.limp_cache_2.setText("")
        self.limpz_servi.setText("")
        self.mem_ptm.setText("")
        self.otm.setText("")
        self.label_52.setText(QCoreApplication.translate("MainWindow", u"10 apps manager", None))
        self.ten_apps.setText("")
        self.label_5.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Ultra Ego FPS", None))
        self.download_ultra_ego_bs.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_7.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Bluestacks 5.20.0.1037", None))
        self.download_5_20_0_1037bs.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_8.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Bluestacks 4.240.1002", None))
        self.download_4_240_1002bs.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_15.setText("")
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"MSI 4.240.15.5318", None))
        self.download_m.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_6.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"MSI Ultra GOD", None))
        self.download_ultra_god_msi.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Anti Crash", None))
        self.label_20.setText("")
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"-----------------------------", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"MSI 5.12", None))
        self.download_msi5_12.setText(QCoreApplication.translate("MainWindow", u"Download", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Tenha Total Consci\u00eancia do que Faz!", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Acelerando o Menu iniciar", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Aumentar Capacidade de Resposta", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Aumente FPS nos Jogos", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Desabilitar Game DVR", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Efeitos Visuais", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"Fullscreen Fix", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Game Optimizations", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Reduzir Input Lag", None))
        self.acelerando_menu.setText("")
        self.aumentar_capacidade.setText("")
        self.aumente_fps.setText("")
        self.des_DVR.setText("")
        self.efeitos_visuais.setText("")
        self.full_screen_fix.setText("")
        self.game_optm.setText("")
        self.red_inp_lag.setText("")
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Desativar Servi\u00e7os", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Desabilitar gerenciador de mapas", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"Desabilitar servi\u00e7os de bluetooth", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Desabilitar servi\u00e7os de impressoras", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Desabilitar servi\u00e7os do Xbox", None))
        self.label_41.setText(QCoreApplication.translate("MainWindow", u"Desabilitar servi\u00e7os extras desnecess\u00e1rios", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Desabilitar UAC", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Desativar Windows Defender", None))
        self.des_maps.setText("")
        self.des_blue.setText("")
        self.des_impre.setText("")
        self.des_xbox.setText("")
        self.des_extr_desn.setText("")
        self.des_uac.setText("")
        self.des_windef.setText("")
    # retranslateUi

